# Chapter 5: Consoles, Windows, MS-DOS
Written by: Woo Jin Lee
Word count: 1047

“We build our computer systems the way we build our cities;
 over time without a plan, on top of ruins.” - Ellen Ullman

---------------------------------------------------------------------------------------------------------------
When it comes to modern computing, especially in the realms of user interface and desktop PCs, Windows is one of the first names people think of. Meaning, in the history of computer science, the triumvirate of MS-DOS, Windows, and Consoles (terminals) all stand as a foundation to technological advancement and human creativity. Each one of them have played a significant role in developing and shaping the computing environment along with creating a user-friendly graphical interface in the computing world. This chapter from the history of computer science will convey the historical and technological aspects of the Console (Terminal), Windows, and MSdos. More importantly, this chapter will talk about their contribution to the overall development of computers and their impact on the modern computing world. 

	## Consoles (Terminals)
Before any graphical user interfaces hit home to the history of computer science, computing primarily revolved around the usage of terminals, also sometimes referred to as consoles. The main purpose for terminals in operating systems was to provide users a command-line interface that would allow users to interact with the underlying operating system they are working on. Users would use the terminals to navigate through, create, and change different files or folders saved in the heart or in the memory of a computer. Algorithms run through the terminal behind the scene, governing various aspects of its functionality; primarily focusing on managing the system resources and parsing through various user commands fed through the command-line.

Besides all the terminal’s functionality found behind the scene, the command interpreter lies at the heart of each terminal found within the operating system, crucially responsible for interpreting and executing commands the user feeds through the command-line interface. This “translator” is how a user is able to communicate with the computer and feed the necessary information to see the desired output. The command interpreter relies on sophisticated algorithmic programming that dissects user inputs to identify commands and execute corresponding outputs. Moreover, the implementation of algorithms for the process management of the terminal and the operational input/output method allows efficient usage of the scarce system resources by providing timely response back to the user. 

Aside from algorithmic developments found within the consoles, also known as the terminal, technological considerations played a huge role in the advancements of the terminal systems the computing world sees now. However, due to major limitations in hardware (e.g. memory constraints or processing power), implementation of lightweight algorithms and optimization of the system was a necessity for efficiency and speed. Moreover, increasing the ability for the terminals to run on diverse hardware structures allowed systems to run seamlessly on a variety of devices. 

  ## Windows
With the introduction of Windows to the world of computing, the ushering era of user-friendly graphical interfaces was introduced, making it one of the most significant historical events in the computing era. Windows is known to provide users with a visually interactive environment including windows, icons, pointers, desktop interface, and different menus. Going into the details of what lies behind all this user interface, a sophisticated framework of algorithms work together in every aspect of the user interface to create this unique, efficient, and user-friendly environment that the user can use to interact with a computer, or an operating system. 

With the introduction of windows came along the introduction of graphics rendering algorithms. They play an important role in bringing the Windows interface to life, giving it all the needed functionality. These computed algorithms accelerate the system performance by creating smooth animations, visual interactions, and more precise on-screen elements all for user interaction. Aside from the graphics rendering algorithms, the input handling algorithm plays a vital role in translating any user actions into meaningful inputs, facilitating meaningful interaction within the Windows environment and the operating system it is running under. 

By understanding the true aspects Windows has brought to the modern computing environment, some technical considerations of the revolutionized technology have driven the advancement of Windows. In particular, memory management, device abstraction, and process scheduling are one of the few things that Windows has brought to the computing environment with its development and introduction in computer science. More importantly, different algorithms inherited and brought into the Windows interface has allowed the operating system to optimize its resource allocation which has significantly ensured the utilization of system resources in a meaningful and efficient manner. In addition to that, in order to facilitate a wide range of hardware configurations, the standardized APIs were added to Windows. As computers deal with expected and unexpected errors all the time, algorithms for recovery and handling significantly enhance the system’s robustness, increasing efficiency and decreasing disruptions any user may experience throughout their interaction with a computer. This in particular is important because prior to the introduction of Windows, computer systems were easily prone to rapid system disruptions. 

  ## MS-DOS
Finally, the Microsoft Disk Operating System, also known as the MS-DOS has served as the cornerstone of early personal computing. MS-DOS provided users with a suite of essential utilities and a command-line interface, similar to the terminal. Despite its seemingless nature of being simple, its robust algorithms introduced in the operating system highly depend on a set of robust algorithms that help facilitate file operations, manage system resources, and execute user and system commands. By introducing a line of different algorithms, including disk accessing, into the operating system, MS-DOS is able to minimize access times while maximizing data throughput and optimize storage performance. Moreover, command parsing algorithms and algorithms for system memory management and process scheduling all ensured optimal system performance. Finally, some of the technological considerations in the history of computing have been shaped by the function and design of MS-DOS, as it has been a cornerstone for early personal-computing. Its compatibility with a vast range of different hardware structures has made it capable in adapting to diverse environments, all of which come to its core algorithmic programing and functionality within the operating system. In particular, continuous questions and problems with the disk storage capacity, processor compatibility, and never ending memory constraints have highly influenced the algorithmic decisions made in the history of computer science. This has both driven innovation and refinement in MS-DOS while driving the advancements of computers and the user computing world, leaving a solidified mark in the history of computer science. 

Bibliography:
1. https://ux.stackexchange.com/questions/101990/why-are-terminal-consoles-still-used
2. https://www.linkedin.com/advice/0/how-do-you-choose-between-terminal-console-your 
3. https://en.wikipedia.org/wiki/Computer_terminal 
4. https://techcommunity.microsoft.com/t5/away-from-keyboard/microsoft-a-journey-of-innovation-and-impact/m-p/4032545# 
5. https://www.windowscentral.com/microsoft-has-had-profound-technological-and-social-global-impact 
6. https://en.wikipedia.org/wiki/MS-DOS 
7. https://www.techtarget.com/searchenterprisedesktop/definition/MS-DOS 
8. https://www.youtube.com/watch?v=QHKzHQuMXE4 
9. https://www.youtube.com/watch?v=H1fhkhCC5l4 

Google Docs Link: https://docs.google.com/document/d/11Yao9rJ3myWbtF-BiGrEzKEW_eawYMNCOitmI9rsENc/edit?usp=sharing 
